.TH "RAWcooked" "1" "https://mediaarea.net/RAWcooked" "18.10.1" "Bit-by-bit fidelity"
.\" Turn off justification for nroff.
.if n .ad l
.\" Turn off hyphenation.
.nh
.SH NAME
\fBRAWcooked\fR - encode and decode audio-visual RAW data with Matroska, FFV1 and FLAC
.SH SYNOPSIS
\fBrawcooked \fR[\fIoption\fR ...] (\fIfolder\fR | \fIfile\fR ...) [\fIoption\fR ...]
.SH DESCRIPTION
.TP
\fBRAWcooked\fR easily encodes RAW audio-visual sequences into a lossless video stream, reducing the file size by between one and two thirds. FFmpeg encodes the audio-visual data into a Matroska container (.mkv) using the video codec FFV1, and audio codec FLAC. The metadata accompanying the RAW data is fully preserved, along with additional sidecar files such as MD5 checksums, LUT or XML if desired. This allows for the management of these audio-visual file formats in an effective and transparent way. The lossless Matroska video stream can be played in VLC or MPV media players, and writing and retrieving from storage devices such as LTO is significantly quicker.
.TP
If you need to use the RAW source in its original form, one line of code will easily restore it \fBbit-by-bit\fR, faster than retrieving the same file from LTO tape storage.
.TP
.I folder
Every image file within the sequence's \fIfolder\fR is encoded into a single FFV1 video stream, and each audio track within the same \fIfolder\fR is encoded to the FLAC codec. Both the FFV1 and FLAC contents are then muxed into a single Matroska container (.mkv).
.br
The image filenames must end in a complete number sequence, so that \fBRAWcooked\fR can parse each image within the sequence in the correct order.
.TP
.I file
.B contains RAW data (e.g. a .dpx or .wav file):
.br
Every image within a sequence folder containing the \fIfile\fR is encoded into a single FFV1 video stream, and each audio track within the folder containing the same \fIfile\fR is encoded to the FLAC codec. Both the FFV1 and FLAC contents are then muxed into a single Matroska container (.mkv).
.br
The image filenames must end in a complete number sequence. By entering one \fIfile\fR within this sequence \fBRAWcooked\fR will parse every image in the correct order.
.TP
.I file
.B is a Matroska container (.mkv):
.br
Decodes the Matroska file back to the original RAW image sequence, including restoration of the original metadata and sidecar files. It is important to stress that the encoded files can be fully decoded, and that this process will create bit-by-bit identical files to the originals. Not only is the image and audio content fully restored, but also all enclosed metadata and all of the file's characteristics. Therefore, an encoded and decoded RAW file cannot be differentiated from its original.
.SH OPTIONS
.SS GENERAL OPTIONS
.TP
.B --help \fR|\fB -h
Displays the help guide.
.TP
.B --version
Tells you which installed version you are using.
.TP
.B --store-license value
Set the license key to value and store on hard drive. (license is stored in ~/.config/RAWcooked/Config.txt on Linux/Mac, %APPDATA%/RAWcooked/Config.txt on Windows)
.TP
.B --show-license
Displays information about the installed license.
.TP
.B --attachment-max-size \fIvalue\fR | \fB-s \fIvalue
Set maximum size of attachments to \fIvalue\fR (in bytes).
.br
The default value is \fI1048576\fR.
.TP
.B --check \fIvalue\fR
Switch the check function on or off. Be aware check function can be demanding of time and processor usage.
.br
\fIpartial\fR (or \fI0\fR) is quicker but may lead to partial reversibility with files that do not conform.
.br
\fIfull\fR (or \fI1\fR) is slower but guarantees reversibility, for example with DPX where the bits do not have any zero padding included.
.br
The default value is 'partial'.
.TP
.B --display-command \fR|\fB -d
When an external encoder/decoder is used, display the command to launch instead of just launching it.
.TP
.B --output-name \fIvalue\fR | \fB-o \fIvalue
Set the name of the output file or folder to \fIvalue\fR.
.br
The default output value is opposite to the input. Expect \fI${Input}.mkv\fR if the input is a folder, or \fI${Input}.RAWcooked\fR if input is a file, such as a DPX.
.TP
.B --rawcooked-file-name \fIvalue\fR | \fB-r \fIvalue
Set during encoding, or retrieve by decoding, the name of the \fBRAWcooked\fR reversibility data file to \fIvalue\fR.
.br
The default name is \fI${Input}.rawcooked_reversibility_data\fR.
.br
\fBNote:\fR This file is deleted after encoding if the \fBRAWcooked\fR reversibility data file is embedded in the output Matroska wrapper during encoding.
.br
\fBNote:\fR Not yet implemented for decoding.
.TP
.B --quiet
Do not show information related to RAWcooked.
.br
External encoder or decoder may need an additional option.
.TP
.B -y
Automatic yes to prompts.
.br
Assume \fIyes\fR in answer to all prompts, and run non-interactively.
.TP
.B -n
Automatic no to prompts.
.br
Assume \fIno\fR as answer to all prompts, and run non-interactively.
.SS ACTIONS
.TP
.B --all
Same as --check --check-padding --coherency --conch --encode --hash (see below)
.TP
.B --none
Same as --no-check --no-coherency --no-conch --no-encode (see below)
.TP
.B --check
Check that the encoded file can be correctly decoded.
.br
If the input is raw content such as DPX, encode then decode the raw input, before checking that the original raw content and the decoded files are identical.
.br
If the input is a Matroska container, decode the input and check that the output is same as the decoded content.
.TP
.B --no-check
Don't run any checks (see above).
.br
This is the default, but may change in the future.
.TP
.B --check-padding
Run padding checks. Be aware check function can be demanding of time and processor usage.
.br
It is a slower process but guarantees reversibility, for example with DPX files that have bits with no zero padding.
.TP
.B --quick-check-padding
Switch to --check-padding or --no-check-padding depending on what is found in the first image.
.br
The program will stop with an error code if --check is not used at the same time and zero-padding bits are in the content, asking to choose what to do.
.br
This is the default, but may change in the future.
.TP
.B --no-check-padding
Do not run padding checks, as they are demanding of time and processor usage.
.br
This method is quicker, but be aware it may lead to partial reversibility with files that do no conform.
.TP
.B --coherency
Checks that the package and contents are coherent.
.br
This is currently partially implemented.
.br
This is default, but may change in the future.
.TP
.B --no-coherency
Do not carry out coherency check (see above).
.TP
.B --conch
Conformance check of the format, effective only when format is supported.
.br
This is currently partially implemented for DPX.
.TP
.B --no-conch
Do not carry out conformance check (see above).
.br
This is default, but may change in the future.
.TP
.B --encode
Encode audio-visual RAW data into a compressed stream.
.br
This is default.
.TP
.B --no-encode
Do not carry out encode (see above).
.TP
.B --hash
Can be used to either compute, or test, the hash of files.
.br
To compute a hash use with the audio-visual RAW data. A hash is generated and stored in the RAWcooked metadata.
.br
Repeat the command with the RAW data to test that the previously generated hash file is valid.
.br
If the input is a Matroska container with metadata that contains computed hashes then decode the Matroska input and check hashes. Any issue raised by the check is considered a decoding error.
.br
If the input is a Matroska container with computed hash files stored in an attachment, then decode the Matroska input and check hashes. Any issue raised by the check is considered as invalid data.
.br
This is default when the input is a Matroska container and RAWcooked metadata contains hashes, and when the input is a Matroska container with hash files in the attachment. This default may change in the future.
.TP
.B --no-hash
Do not compute or test the hash of the file (see above).
.br
This is default when the input is RAW content, but may change in the future.
.TP
.B --framemd5
Compute the framemd5 of input frames and store it to a sidecar file.
.br
See FFmpeg framemd5 documentation for more information.
.TP
.B --framemd5-name \fIvalue\fR
Set the name of the framemd5 file to \fIvalue\fR.
.br
Default value is \fI${Input}.framemd5\fR.
.TP
.B --no-framemd5
Do not compute of framemd5 of input frames. (see above)."
.br
Is default.
.SS INPUT RELATED OPTIONS
.TP
.B --file
Unlock the compression of files, for example with .dpx or .wav.
.TP
.B -framerate \fIvalue
Force the video frame rate value to \fIvalue\fR.
.br
Default frame rate value is found in the image file metadata, if available. Otherwise it will default to \fI24\fR.
.SS ENCODING RELATED OPTIONS
.TP
.B -c:a \fIvalue
Use this command to force the audio encoding format to \fIvalue\fR: \fIcopy\fR (for example copy PCM to PCM, without modification), \fIFLAC\fR
.br
The default value is \fIFLAC\fR.
.TP
.B -c:v \fIvalue
Force the video encoding format \fIvalue\fR: only \fIffv1\fR is currently allowed, which is the default value.
.TP
.B -coder \fIvalue
If video encoding format is \fIffv1\fR, set the Coder to \fIvalue\fR: \fI0\fR (Golomb-Rice), \fI1\fR (Range Coder), \fI2\fR (Range Coder with custom state transition table).
.br
The default value is \fI1\fR.
.TP
.B -context \fIvalue
If the video encoding format is \fIffv1\fR, set the Context to \fIvalue\fR: \fI0\fR (small), \fI1\fR (large).
.br
The default value is \fI0\fR.
.TP
.B -format \fIvalue
Set the container format to \fIvalue\fR: only \fImatroska\fR is currently allowed, which is the default value.
.TP
.B -g \fIvalue
If video encoding format is \fIffv1\fR, set the GOP size to \fIvalue\fR\: \fI1\fR (generates a strict intra-frame bitstream), \fI0\fR (allows adaptable context model across frames).
.br
The default value is \fI1\fR. Ensure you leave the setting at \fI1\fR for archival use.
.TP
.B -level \fIvalue
The video encoding format \fIffv1\fR can have Version set to \fIvalue\fR: \fI0\fR, \fI1\fR, \fI3\fR.
.br
The default value is the latest version \fI3\fR.
.TP
.B -slicecrc \fIvalue
If video encoding format is \fIffv1\fR, you can set the CRC checksum to \fIvalue\fR: \fI0\fR (CRC checksums off), \fI1\fR (CRC checksum on).
.br
The default value is \fI1\fR.
.TP
.B -slices \fIvalue
If the video encoding format is \fIffv1\fR, you can set the multithreaded encoding slices to \fIvalue\fR: any integer over 1 (it is recommended to use a figure divisible by your workstations CPU core processors such as 2, 4, 6, 9, 16, 24...).
.br
The default value is variable between \fI16\fR and \fI512\fR, depending on the video frame size and depth.
.SH COPYRIGHT
Copyright (c) 2018-2020 MediaArea.net SARL & AV Preservation by reto.ch
.SH LICENSE
\fBRAWcooked\fR is released under a BSD License.
.SH DISCLAIMER
\fBRAWcooked\fR is provided "as is" without warranty or support of any kind.
