.TH "RAWcooked" "1" "https://mediaarea\.net/RAWcooked" "18\.01" "Bit\-by\-bit fidelity"
.SH NAME
\fBRAWcooked\fR \- encode and decode audio\-visual RAW data with Matroska, FFV1 and FLAC
.SH SYNOPSIS
.
.SS
\fBrawcooked \fIfolder\fR | \fIfile
.TP
.I folder
Encodes with the FFV1 video codec all single\-image video files in the \fIfolder\fR, encodes with the FLAC audio codec all audio files in the \fIfolder\fR, and muxes these into a Matroska container (\.mkv)\.
.br
The filenames of the single image files must end with a numbered sequence\. \fBRAWcooked\fR will generate the regex to parse in the correct order all the frames in the folder\.
.TP
.I file
.B contains RAW data (e\.g\. a \.dpx or \.wav file):
.br
Encodes with the FFV1 video codec all single\-image video files in the folder containing the \fIfile\fR, encodes with the FLAC audio codec all audio files in the folder containing the \fIfile\fR, and muxes these into a Matroska container (\.mkv)\.
.br
The filenames usually end with a numbered sequence\. Enter one frame and the tool will generate the regex to parse all the frames in the folder\.
.TP
.I file
.B is a Matroska container (\.mkv):
.br
Decodes back the video and the audio of \fIfile\fR to its original formats\. All metadata accompanying the original data are preserved bit\-by\-bit\.
.
.SS
\fBrawcooked \-e \fR(\fIfolder\fR | \fIfile\fR)
.TP
.B \-e
Encodes the \fIfile\fRs in the \fIfolder\fR or the \fIfile\fR as above\.
.LP
Caveat: The \-e parameter has not been implemented yet.
.
.SS
\fBrawcooked \-d \fIfile
.TP
.B \-d
Decodes the Matroska \fIfile\fR back to the original data as above\.
.LP
Caveat: The \-d parameter has not been implemented yet.
.
.SS
\fBrawcooked \-h | \-\-help
.TP
.B \-h | \-\-help
Displays a help message\.
.
.SS
\fBrawcooked \-v | \-\-version
.TP
.B \-v | \-\-version
Displays the installed version\.
.SH DESCRIPTION
.TP
\fBRAWcooked\fR encodes audio\-visual RAW data into the Matroska container (MKV), using the video codec FFV1 for the image and audio codec FLAC for the sound\. The metadata accompanying the RAW data are preserved, and sidecar files, like MD5, LUT or XML, can be added into the Matroska container as attachments\. This allows for the management of these audio\-visual file formats in an effective and transparent way (e\.g\. native playback in VLC), while saving typically between one to two thirds of the needed storage, and speeding up the back\-up process on LTO cartridges\.
.TP
When needed, the uncompressed source is retrieved \fBbit\-by\-bit\fR, in a manner faster than uncompressed sources directly stored on LTO cartridges\.
.
.SH COPYRIGHT
Copyright (c) 2018 MediaArea\.net SARL & AV Preservation by reto\.ch
.SH LICENSE
\fBRAWcooked\fR is released under a BSD License\.
.SH DISCLAIMER
\fBRAWcooked\fR is provided "as is" without warranty or support of any kind\.
